language: node_js

node_js:
  - 10
  - 8

before_install:
  - travis_retry yarn add --peer react react-native react-native-svg

install:
  - travis_retry yarn

script:
  - yarn test --coverage

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - yarn test --coverage
        - yarn build
      after_success:
        - yarn codecov
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
